### ISSUE TITLE
Broken %PATH% for the regular cmd environment

### ISSUE THREAD

**Issue by grzegorzkrukowski** [compnerd/gha-setup-swift#41]
After running the installation all the %PATH% values are gone on the regular `cmd` shell.

```
- name: Debug PATH before Swift installation
  shell: pwsh
  run: |
    Write-Host "PATH before Swift installation:"
    Write-Host $env:PATH
- name: Debug PATH in cmd shell
  shell: cmd
  run: |
    echo %PATH%
- name: Install Swift toolchain
  uses: compnerd/gha-setup-swift@main
  with:
    branch: swift-${{ env.SWIFT_VERSOIN }}-release
    tag: ${{ env.SWIFT_VERSOIN }}-RELEASE
- name: Debug PATH after Swift installation
  shell: pwsh
  run: |
    Write-Host "PATH after Swift installation:"
    Write-Host $env:PATH
- name: Debug PATH in cmd shell
  shell: cmd
  run: |
    echo %PATH%
```

The `pwsh` works as expected, but the `cmd` %PATH% is empty after running the swift installation.
