### ISSUE TITLE
Setup on windows-2019 fails with: "Could not find a part of the path 'D:\Include\ucrt\module.modulemap'."

### ISSUE THREAD

**Issue by marcprux** [compnerd/gha-setup-swift#45]
My Windows [ci.yml](https://github.com/skiptools/swift-sqlcipher/blob/main/.github/workflows/ci.yml) just started failing yesterday (since https://github.com/compnerd/gha-setup-swift/commit/17be5ca66ad69b44177f01b6b0b23575d3d7791a):

```yml
  windows:
    runs-on: windows-2019
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.9-release
          tag: 5.9-RELEASE
      - uses: actions/checkout@v4
      - run: swift test
```

Here's the [error](https://github.com/skiptools/swift-sqlcipher/actions/runs/14462860880/job/40558596457):

```
install: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
vsdevcmd: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\vsdevcmd.bat
$ cmd /q /k C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\vsdevcmd.bat -arch=amd64 && set
environment updated
Run Copy-Item "$env:SDKROOT\usr\share\ucrt.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\ucrt\module.modulemap"
Copy-Item: D:\a\_temp\bce433de-ba56-4c96-a620-b77ea2e737f3.ps1:2
Line |
   2 |  Copy-Item "$env:SDKROOT\usr\share\ucrt.modulemap" -destination "$env: …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path 'D:\Include\ucrt\module.modulemap'.
Error: Process completed with exit code 1.
```
